import type { Metadata } from "next";
import PolicyLayout from "@/components/PolicyLayout";

export const metadata: Metadata = {
  title: "Terms of Service — The Changelog",
  description: "The Changelog terms of service. Governing your use of the app.",
};

export default function TermsPage() {
  return (
    <PolicyLayout title="TERMS OF SERVICE" updated="FEBRUARY 2026">

      <p>
        These Terms of Service ("Terms") govern your use of The Changelog mobile application ("the App")
        operated by us. By downloading or using the App, you agree to these Terms.
      </p>

      <h2>1. ACCEPTANCE OF TERMS</h2>
      <p>
        By accessing or using The Changelog, you agree to be bound by these Terms and our Privacy Policy.
        If you do not agree to these Terms, do not use the App.
      </p>

      <h2>2. USE OF THE APP</h2>
      <p>
        The Changelog is a news aggregation app that provides AI-summarized tech news stories. You may
        use the App for personal, non-commercial purposes only.
      </p>
      <p>You agree not to:</p>
      <ul>
        <li>Use the App for any unlawful purpose or in violation of any applicable laws</li>
        <li>Attempt to reverse engineer, decompile, or extract source code from the App</li>
        <li>Use automated tools, bots, or scrapers to access our API or content</li>
        <li>Attempt to circumvent any security or rate-limiting measures</li>
        <li>Reproduce, redistribute, or sell content from the App without permission</li>
      </ul>

      <h2>3. CONTENT AND INTELLECTUAL PROPERTY</h2>
      <p>
        News article content displayed in the App originates from third-party publishers. Summaries are
        generated by AI and are provided for informational purposes only. Original articles remain the
        property of their respective publishers.
      </p>
      <p>
        The Changelog's design, branding, and codebase are our intellectual property. The Changelog
        name and logo may not be used without written permission.
      </p>

      <h2>4. ACCURACY OF CONTENT</h2>
      <p>We strive to surface accurate, relevant news. However:</p>
      <ul>
        <li>AI-generated summaries may contain errors or omissions</li>
        <li>We do not verify the accuracy of content from third-party sources</li>
        <li>
          News content should not be relied upon for financial, medical, legal, or professional advice
        </li>
        <li>Always read the original article before acting on any information</li>
      </ul>

      <h2>5. ADVERTISING</h2>
      <p>
        The Changelog is free and supported by advertising through Google AdMob. Interstitial ads may
        be displayed periodically while using the App. We do not control ad content beyond what AdMob's
        platform permits.
      </p>

      <h2>6. AVAILABILITY AND CHANGES</h2>
      <p>
        We reserve the right to modify, suspend, or discontinue the App at any time without notice. We
        may update the App, add or remove features, or change content sources at our discretion.
      </p>
      <p>
        We are not liable for any loss resulting from unavailability of the App or changes to its
        functionality.
      </p>

      <h2>7. DISCLAIMER OF WARRANTIES</h2>
      <p>
        THE APP IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. WE DISCLAIM ALL
        WARRANTIES INCLUDING FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABILITY, AND NON-INFRINGEMENT.
      </p>

      <h2>8. LIMITATION OF LIABILITY</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
        SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE APP.
      </p>

      <h2>9. THIRD-PARTY LINKS</h2>
      <p>
        The App may link to third-party websites (original news articles). We are not responsible for
        the content, privacy practices, or terms of those external sites. Visiting them is at your own
        risk.
      </p>

      <h2>10. TERMINATION</h2>
      <p>
        We may terminate or restrict your access to the App if we believe you have violated these Terms.
        You may terminate your use of the App at any time by deleting it from your device.
      </p>

      <h2>11. GOVERNING LAW</h2>
      <p>
        These Terms are governed by the laws of British Columbia, Canada, without regard to conflict of
        law provisions. Any disputes shall be resolved in the courts of British Columbia.
      </p>

      <h2>12. CHANGES TO TERMS</h2>
      <p>
        We may update these Terms at any time. Material changes will be communicated through the App.
        Continued use constitutes acceptance of updated Terms.
      </p>

      <h2>13. CONTACT</h2>
      <p>
        Questions about these Terms? Contact us at:{" "}
        <a href="mailto:sharvarid.dev@gmail.com">sharvarid.dev@gmail.com</a>
      </p>

    </PolicyLayout>
  );
}
